/**
 * \file        main.c
 * \brief       This proyect implements an digital signal generator. 
 * \details     In this practice, we will develop a Digital Signal Generator (DSG) device. 
 * The DSG device generates 4 different waveforms: sine, triangular, sawtooth, and square. 
 * The user can select the type of waveform generated by the DSG using a push button. 
 * Each time the button is pressed, the system switches from one waveform to the next sequentially. 
 * The amplitude, DC level (offset), and signal frequency are entered using a 4x4 matrix keypad. 
 * To enter the amplitude, the user will press the A key followed by the desired voltage value in 
 * millivolts and the D key to finalize. Similarly, to enter the DC level, the user will press 
 * the B key followed by the desired DC voltage value in millivolts and the D key to finalize. 
 * Finally, to enter the frequency, the user must press the C key followed by the frequency 
 * value in Hertz and the D key to finalize. The current values of Amplitude, DC Level, and 
 * Frequency along with the current waveform will be printed every second via the serial or USB 
 * interface to a terminal tool. 
 * 
 * The Amplitude should be adjustable between 100mV and 2500mV, the DC Level between 50mV and 1250mV. 
 * The frequency should be adjustable between 1 Hz and 12000000 Hz. 
 * Therefore, the max range for the value of the signal is: -2450mV to 3750mV.
 * 
 * By default, the DSG device starts generating a sinusoidal signal with an amplitude of 1000 mV, 
 * DC Level of 500mV, and frequency of 10Hz. The generated signal and its characteristics 
 * should be able to be verified by a measuring instrument, multimeter, or oscilloscope.
 * 
 * \author      Ricardo Andres Velásquez
 * \version     0.0.1
 * \date        05/10/2023
 * \copyright   Unlicensed
 * 
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <math.h>
#include "pico/stdlib.h"
#include "hardware/timer.h"

#include "time_base.h"
#include "keypad_polling.h"
#include "gpio_led.h"
#include "gpio_button.h"
#include "signal_generator.h"
#include "functions.h"


int main() {
    
    stdio_init_all();
    sleep_ms(5000);
    printf("Hola!!!");

    uint8_t in_param_state = 0x0; // 0: Nothing, 1: Entering amp (A), 2: Entering offset (B), 3: Entering freq (D)
    uint8_t in_signal_state = 0x0; // 0: Sinusoidal, 1: Triangular, 2: Saw tooth, 3: Square
    signal_t signal;

    key_pad_t my_keypad;
    kp_init(&my_keypad,2,6,100000,true);

    gpio_button_t my_button;
    button_init(&my_button, 0, 100000, true);

    while(1){
        // Process keypad
        uint32_t cols = gpio_get_all() & (0x0000003C);
        if(cols && !my_keypad.KEY.dbnc){
            //printf("%d\n",cols);
            tb_disable(&my_keypad.tb_seq);
            kp_capture(&my_keypad,cols);
            tb_update(&my_keypad.tb_dbnce);
            tb_enable(&my_keypad.tb_dbnce);
            kp_set_zflag(&my_keypad);
            my_keypad.KEY.dbnc = 1;
        }
        if(tb_check(&my_keypad.tb_seq)){
            tb_next(&my_keypad.tb_seq);
            kp_gen_seq(&my_keypad);
            //printf("%d\n",my_keypad.KEY.seq);
        }
        if(tb_check(&my_keypad.tb_dbnce)){
            tb_next(&my_keypad.tb_dbnce);
            if(kp_is_2nd_zero(&my_keypad)){
                if(!cols){
                    // This able to generate seq only when a button is not pressed
                    tb_update(&my_keypad.tb_seq); // It could happens that a button was pressed for a long time
                    tb_enable(&my_keypad.tb_seq);
                    tb_disable(&my_keypad.tb_dbnce);
                    my_keypad.KEY.dbnc = 0;
                }
                else
                    kp_clr_zflag(&my_keypad);
            }
            else{
                if(!cols)
                    kp_set_zflag(&my_keypad);
            }
        }
        // Process button
        bool button = gpio_get(my_button.KEY.pin);
        if(button && !my_button.KEY.dbnc){
            my_button.KEY.nkey = true; // This is a flag that indicates that a key was pressed
            tb_update(&my_button.tb_dbnce); 
            tb_enable(&my_button.tb_dbnce);
            button_set_zflag(&my_button);
            my_button.KEY.dbnc = 1;
        }
        if(tb_check(&my_button.tb_dbnce)){
            tb_next(&my_button.tb_dbnce);
            if(button_is_2nd_zero(&my_button)){
                if(!button){
                    // printf("Button pressed\n");
                    in_signal_state = (in_signal_state + 1) % 4;
                    tb_disable(&my_button.tb_dbnce);
                    my_button.KEY.dbnc = 0;
                }
                else
                    button_clr_zflag(&my_button);
            }
            else{
                if(!button)
                    button_set_zflag(&my_button);
            }
        }
    }

    return 1;
}